# Generated by Django 6.0.3 on 2026-03-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=100)),
                ('hero_title', models.CharField(max_length=500)),
                ('hero_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ApproachSection',
            new_name='Home_ApproachSection',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
